namespace POS.Register.Types;

public record DrawerMovementDto(
    Guid Id,
    decimal Amount,
    string Note,
    bool IsVoided,
    DateTime CreatedAt);

public record ShiftReadDto(
    Guid Id,
    int Number,
    bool IsClosed,
    DateTime OpenedAt,
    DateTime? ClosedAt,
    decimal StartingCash,
    decimal? StartingCashOriginal,
    string? StartingCashCorrectionReason,
    decimal NetSales,
    int TransactionCount,
    decimal Refunds,
    int RefundCount,
    decimal CashSales,
    decimal GcashSales,
    decimal MayaSales,
    int EWalletCashInCount,
    decimal EWalletCashIn,
    int EWalletCashOutCount,
    decimal EWalletCashOut,
    decimal DrawerMovementsNet,
    decimal ExpectedCash,
    decimal? CountedCash,
    decimal? CountedCashOriginal,
    string? CorrectionReason,
    decimal? CashVariance,
    decimal? StartingEWalletBalance,
    decimal? ExpectedEWalletBalance,
    decimal? CountedEWalletBalance,
    decimal? EWalletVariance,
    List<DrawerMovementDto> Movements);
